// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_A_conv1_pragma (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_address0,
        x_ce0,
        x_q0,
        x_address1,
        x_ce1,
        x_q1,
        y_0_address1,
        y_0_ce1,
        y_0_we1,
        y_0_d1,
        y_1_address1,
        y_1_ce1,
        y_1_we1,
        y_1_d1
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] x_address0;
output   x_ce0;
input  [7:0] x_q0;
output  [9:0] x_address1;
output   x_ce1;
input  [7:0] x_q1;
output  [10:0] y_0_address1;
output   y_0_ce1;
output   y_0_we1;
output  [7:0] y_0_d1;
output  [10:0] y_1_address1;
output   y_1_ce1;
output   y_1_we1;
output  [7:0] y_1_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] LENET_C1_W_0_0_0_address0;
reg    LENET_C1_W_0_0_0_ce0;
wire   [6:0] LENET_C1_W_0_0_0_q0;
wire   [1:0] LENET_C1_W_0_0_1_address0;
reg    LENET_C1_W_0_0_1_ce0;
wire   [6:0] LENET_C1_W_0_0_1_q0;
wire   [1:0] LENET_C1_W_0_0_2_address0;
reg    LENET_C1_W_0_0_2_ce0;
wire   [7:0] LENET_C1_W_0_0_2_q0;
wire   [1:0] LENET_C1_W_0_0_3_address0;
reg    LENET_C1_W_0_0_3_ce0;
wire   [6:0] LENET_C1_W_0_0_3_q0;
wire   [1:0] LENET_C1_W_0_0_4_address0;
reg    LENET_C1_W_0_0_4_ce0;
wire   [7:0] LENET_C1_W_0_0_4_q0;
wire   [1:0] LENET_C1_W_0_1_0_address0;
reg    LENET_C1_W_0_1_0_ce0;
wire   [6:0] LENET_C1_W_0_1_0_q0;
wire   [1:0] LENET_C1_W_0_1_1_address0;
reg    LENET_C1_W_0_1_1_ce0;
wire   [5:0] LENET_C1_W_0_1_1_q0;
wire   [1:0] LENET_C1_W_0_1_2_address0;
reg    LENET_C1_W_0_1_2_ce0;
wire   [6:0] LENET_C1_W_0_1_2_q0;
wire   [1:0] LENET_C1_W_0_1_3_address0;
reg    LENET_C1_W_0_1_3_ce0;
wire   [7:0] LENET_C1_W_0_1_3_q0;
wire   [1:0] LENET_C1_W_0_1_4_address0;
reg    LENET_C1_W_0_1_4_ce0;
wire   [7:0] LENET_C1_W_0_1_4_q0;
wire   [1:0] LENET_C1_W_0_2_0_address0;
reg    LENET_C1_W_0_2_0_ce0;
wire   [6:0] LENET_C1_W_0_2_0_q0;
wire   [1:0] LENET_C1_W_0_2_1_address0;
reg    LENET_C1_W_0_2_1_ce0;
wire   [6:0] LENET_C1_W_0_2_1_q0;
wire   [1:0] LENET_C1_W_0_2_2_address0;
reg    LENET_C1_W_0_2_2_ce0;
wire   [7:0] LENET_C1_W_0_2_2_q0;
wire   [1:0] LENET_C1_W_0_2_3_address0;
reg    LENET_C1_W_0_2_3_ce0;
wire   [7:0] LENET_C1_W_0_2_3_q0;
wire   [1:0] LENET_C1_W_0_2_4_address0;
reg    LENET_C1_W_0_2_4_ce0;
wire   [7:0] LENET_C1_W_0_2_4_q0;
wire   [1:0] LENET_C1_W_0_3_0_address0;
reg    LENET_C1_W_0_3_0_ce0;
wire   [6:0] LENET_C1_W_0_3_0_q0;
wire   [1:0] LENET_C1_W_0_3_1_address0;
reg    LENET_C1_W_0_3_1_ce0;
wire   [7:0] LENET_C1_W_0_3_1_q0;
wire   [1:0] LENET_C1_W_0_3_2_address0;
reg    LENET_C1_W_0_3_2_ce0;
wire   [7:0] LENET_C1_W_0_3_2_q0;
wire   [1:0] LENET_C1_W_0_3_3_address0;
reg    LENET_C1_W_0_3_3_ce0;
wire   [7:0] LENET_C1_W_0_3_3_q0;
wire   [1:0] LENET_C1_W_0_3_4_address0;
reg    LENET_C1_W_0_3_4_ce0;
wire   [7:0] LENET_C1_W_0_3_4_q0;
wire   [1:0] LENET_C1_W_0_4_0_address0;
reg    LENET_C1_W_0_4_0_ce0;
wire   [7:0] LENET_C1_W_0_4_0_q0;
wire   [1:0] LENET_C1_W_0_4_1_address0;
reg    LENET_C1_W_0_4_1_ce0;
wire   [7:0] LENET_C1_W_0_4_1_q0;
wire   [1:0] LENET_C1_W_0_4_2_address0;
reg    LENET_C1_W_0_4_2_ce0;
wire   [6:0] LENET_C1_W_0_4_2_q0;
wire   [1:0] LENET_C1_W_0_4_3_address0;
reg    LENET_C1_W_0_4_3_ce0;
wire   [7:0] LENET_C1_W_0_4_3_q0;
wire   [1:0] LENET_C1_W_0_4_4_address0;
reg    LENET_C1_W_0_4_4_ce0;
wire   [7:0] LENET_C1_W_0_4_4_q0;
reg   [1:0] oc_1_reg_611;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln117_fu_515_p2;
wire   [6:0] sub_ln131_fu_583_p2;
reg   [6:0] sub_ln131_reg_746;
wire    ap_CS_fsm_state3;
wire   [14:0] acc_fu_590_p6;
reg   [14:0] acc_reg_751;
reg   [6:0] LENET_C1_W_0_0_0_load_reg_756;
reg   [6:0] LENET_C1_W_0_0_1_load_reg_761;
reg   [7:0] LENET_C1_W_0_0_2_load_reg_766;
reg   [6:0] LENET_C1_W_0_0_3_load_reg_771;
reg   [7:0] LENET_C1_W_0_0_4_load_reg_776;
reg   [6:0] LENET_C1_W_0_1_0_load_reg_781;
reg   [5:0] LENET_C1_W_0_1_1_load_reg_786;
reg   [6:0] LENET_C1_W_0_1_2_load_reg_791;
reg   [7:0] LENET_C1_W_0_1_3_load_reg_796;
reg   [7:0] LENET_C1_W_0_1_4_load_reg_801;
reg   [6:0] LENET_C1_W_0_2_0_load_reg_806;
reg   [6:0] LENET_C1_W_0_2_1_load_reg_811;
reg   [7:0] LENET_C1_W_0_2_2_load_reg_816;
reg   [7:0] LENET_C1_W_0_2_3_load_reg_821;
reg   [7:0] LENET_C1_W_0_2_4_load_reg_826;
reg   [6:0] LENET_C1_W_0_3_0_load_reg_831;
reg   [7:0] LENET_C1_W_0_3_1_load_reg_836;
reg   [7:0] LENET_C1_W_0_3_2_load_reg_841;
reg   [7:0] LENET_C1_W_0_3_3_load_reg_846;
reg   [7:0] LENET_C1_W_0_3_4_load_reg_851;
reg   [7:0] LENET_C1_W_0_4_0_load_reg_856;
reg   [7:0] LENET_C1_W_0_4_1_load_reg_861;
reg   [6:0] LENET_C1_W_0_4_2_load_reg_866;
reg   [7:0] LENET_C1_W_0_4_3_load_reg_871;
reg   [7:0] LENET_C1_W_0_4_4_load_reg_876;
wire    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start;
wire    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_done;
wire    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_idle;
wire    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_ready;
wire   [9:0] grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_address0;
wire    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_ce0;
wire   [9:0] grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_address1;
wire    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_ce1;
wire   [10:0] grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_address1;
wire    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_ce1;
wire    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_we1;
wire   [7:0] grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_d1;
wire   [10:0] grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_address1;
wire    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_ce1;
wire    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_we1;
wire   [7:0] grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_d1;
reg    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln117_fu_527_p1;
reg   [1:0] oc_fu_116;
wire   [1:0] add_ln117_fu_521_p2;
wire   [5:0] tmp_fu_561_p3;
wire   [2:0] tmp_6_fu_572_p3;
wire   [6:0] zext_ln131_fu_568_p1;
wire   [6:0] zext_ln131_3_fu_579_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start_reg = 1'b0;
end

top_A_conv1_pragma_LENET_C1_W_0_0_0_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_0_0_address0),
    .ce0(LENET_C1_W_0_0_0_ce0),
    .q0(LENET_C1_W_0_0_0_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_0_1_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_0_1_address0),
    .ce0(LENET_C1_W_0_0_1_ce0),
    .q0(LENET_C1_W_0_0_1_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_0_2_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_0_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_0_2_address0),
    .ce0(LENET_C1_W_0_0_2_ce0),
    .q0(LENET_C1_W_0_0_2_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_0_3_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_0_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_0_3_address0),
    .ce0(LENET_C1_W_0_0_3_ce0),
    .q0(LENET_C1_W_0_0_3_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_0_4_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_0_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_0_4_address0),
    .ce0(LENET_C1_W_0_0_4_ce0),
    .q0(LENET_C1_W_0_0_4_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_1_0_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_1_0_address0),
    .ce0(LENET_C1_W_0_1_0_ce0),
    .q0(LENET_C1_W_0_1_0_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_1_1_ROM_AUTO_1R #(
    .DataWidth( 6 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_1_1_address0),
    .ce0(LENET_C1_W_0_1_1_ce0),
    .q0(LENET_C1_W_0_1_1_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_1_2_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_1_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_1_2_address0),
    .ce0(LENET_C1_W_0_1_2_ce0),
    .q0(LENET_C1_W_0_1_2_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_1_3_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_1_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_1_3_address0),
    .ce0(LENET_C1_W_0_1_3_ce0),
    .q0(LENET_C1_W_0_1_3_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_1_4_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_1_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_1_4_address0),
    .ce0(LENET_C1_W_0_1_4_ce0),
    .q0(LENET_C1_W_0_1_4_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_2_0_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_2_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_2_0_address0),
    .ce0(LENET_C1_W_0_2_0_ce0),
    .q0(LENET_C1_W_0_2_0_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_2_1_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_2_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_2_1_address0),
    .ce0(LENET_C1_W_0_2_1_ce0),
    .q0(LENET_C1_W_0_2_1_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_2_2_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_2_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_2_2_address0),
    .ce0(LENET_C1_W_0_2_2_ce0),
    .q0(LENET_C1_W_0_2_2_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_2_3_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_2_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_2_3_address0),
    .ce0(LENET_C1_W_0_2_3_ce0),
    .q0(LENET_C1_W_0_2_3_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_2_4_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_2_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_2_4_address0),
    .ce0(LENET_C1_W_0_2_4_ce0),
    .q0(LENET_C1_W_0_2_4_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_3_0_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_3_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_3_0_address0),
    .ce0(LENET_C1_W_0_3_0_ce0),
    .q0(LENET_C1_W_0_3_0_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_3_1_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_3_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_3_1_address0),
    .ce0(LENET_C1_W_0_3_1_ce0),
    .q0(LENET_C1_W_0_3_1_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_3_2_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_3_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_3_2_address0),
    .ce0(LENET_C1_W_0_3_2_ce0),
    .q0(LENET_C1_W_0_3_2_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_3_3_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_3_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_3_3_address0),
    .ce0(LENET_C1_W_0_3_3_ce0),
    .q0(LENET_C1_W_0_3_3_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_3_4_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_3_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_3_4_address0),
    .ce0(LENET_C1_W_0_3_4_ce0),
    .q0(LENET_C1_W_0_3_4_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_4_0_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_4_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_4_0_address0),
    .ce0(LENET_C1_W_0_4_0_ce0),
    .q0(LENET_C1_W_0_4_0_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_4_1_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_4_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_4_1_address0),
    .ce0(LENET_C1_W_0_4_1_ce0),
    .q0(LENET_C1_W_0_4_1_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_4_2_ROM_AUTO_1R #(
    .DataWidth( 7 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_4_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_4_2_address0),
    .ce0(LENET_C1_W_0_4_2_ce0),
    .q0(LENET_C1_W_0_4_2_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_4_3_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_4_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_4_3_address0),
    .ce0(LENET_C1_W_0_4_3_ce0),
    .q0(LENET_C1_W_0_4_3_q0)
);

top_A_conv1_pragma_LENET_C1_W_0_4_4_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
LENET_C1_W_0_4_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(LENET_C1_W_0_4_4_address0),
    .ce0(LENET_C1_W_0_4_4_ce0),
    .q0(LENET_C1_W_0_4_4_q0)
);

top_A_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3 grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start),
    .ap_done(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_done),
    .ap_idle(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_idle),
    .ap_ready(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_ready),
    .sub_ln131(sub_ln131_reg_746),
    .x_address0(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_address0),
    .x_ce0(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_ce0),
    .x_q0(x_q0),
    .x_address1(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_address1),
    .x_ce1(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_ce1),
    .x_q1(x_q1),
    .y_0_address1(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_address1),
    .y_0_ce1(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_ce1),
    .y_0_we1(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_we1),
    .y_0_d1(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_d1),
    .y_1_address1(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_address1),
    .y_1_ce1(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_ce1),
    .y_1_we1(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_we1),
    .y_1_d1(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_d1),
    .LENET_C1_W_0_4_0_load_cast(LENET_C1_W_0_4_0_load_reg_856),
    .LENET_C1_W_0_2_3_load_cast(LENET_C1_W_0_2_3_load_reg_821),
    .LENET_C1_W_0_4_2_load_cast(LENET_C1_W_0_4_2_load_reg_866),
    .LENET_C1_W_0_1_2_load_cast(LENET_C1_W_0_1_2_load_reg_791),
    .LENET_C1_W_0_1_3_load_cast(LENET_C1_W_0_1_3_load_reg_796),
    .LENET_C1_W_0_2_2_load_cast(LENET_C1_W_0_2_2_load_reg_816),
    .LENET_C1_W_0_3_3_load_cast(LENET_C1_W_0_3_3_load_reg_846),
    .LENET_C1_W_0_1_1_load_cast(LENET_C1_W_0_1_1_load_reg_786),
    .LENET_C1_W_0_0_0_load_cast(LENET_C1_W_0_0_0_load_reg_756),
    .LENET_C1_W_0_1_4_load_cast(LENET_C1_W_0_1_4_load_reg_801),
    .LENET_C1_W_0_4_3_load_cast(LENET_C1_W_0_4_3_load_reg_871),
    .LENET_C1_W_0_2_1_load_cast(LENET_C1_W_0_2_1_load_reg_811),
    .LENET_C1_W_0_1_0_load_cast(LENET_C1_W_0_1_0_load_reg_781),
    .LENET_C1_W_0_4_1_load_cast(LENET_C1_W_0_4_1_load_reg_861),
    .LENET_C1_W_0_0_1_load_cast(LENET_C1_W_0_0_1_load_reg_761),
    .LENET_C1_W_0_0_4_load_cast(LENET_C1_W_0_0_4_load_reg_776),
    .LENET_C1_W_0_3_4_load_cast(LENET_C1_W_0_3_4_load_reg_851),
    .LENET_C1_W_0_0_3_load_cast(LENET_C1_W_0_0_3_load_reg_771),
    .LENET_C1_W_0_2_0_load_cast(LENET_C1_W_0_2_0_load_reg_806),
    .LENET_C1_W_0_3_0_load_cast(LENET_C1_W_0_3_0_load_reg_831),
    .LENET_C1_W_0_3_1_load_cast(LENET_C1_W_0_3_1_load_reg_836),
    .LENET_C1_W_0_2_4_load_cast(LENET_C1_W_0_2_4_load_reg_826),
    .LENET_C1_W_0_0_2_load_cast(LENET_C1_W_0_0_2_load_reg_766),
    .LENET_C1_W_0_3_2_load_cast(LENET_C1_W_0_3_2_load_reg_841),
    .sext_ln118(LENET_C1_W_0_4_4_load_reg_876),
    .merge_i_cast(acc_reg_751)
);

top_A_mux_4_2_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .din2_WIDTH( 15 ),
    .din3_WIDTH( 15 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 15 ))
mux_4_2_15_1_1_U96(
    .din0(15'd3563),
    .din1(15'd32559),
    .din2(15'd23266),
    .din3(15'd23266),
    .din4(oc_1_reg_611),
    .dout(acc_fu_590_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start_reg <= 1'b1;
        end else if ((grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_ready == 1'b1)) begin
            grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        oc_fu_116 <= 2'd0;
    end else if (((icmp_ln117_fu_515_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        oc_fu_116 <= add_ln117_fu_521_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        LENET_C1_W_0_0_0_load_reg_756 <= LENET_C1_W_0_0_0_q0;
        LENET_C1_W_0_0_1_load_reg_761 <= LENET_C1_W_0_0_1_q0;
        LENET_C1_W_0_0_2_load_reg_766 <= LENET_C1_W_0_0_2_q0;
        LENET_C1_W_0_0_3_load_reg_771 <= LENET_C1_W_0_0_3_q0;
        LENET_C1_W_0_0_4_load_reg_776 <= LENET_C1_W_0_0_4_q0;
        LENET_C1_W_0_1_0_load_reg_781 <= LENET_C1_W_0_1_0_q0;
        LENET_C1_W_0_1_1_load_reg_786 <= LENET_C1_W_0_1_1_q0;
        LENET_C1_W_0_1_2_load_reg_791 <= LENET_C1_W_0_1_2_q0;
        LENET_C1_W_0_1_3_load_reg_796 <= LENET_C1_W_0_1_3_q0;
        LENET_C1_W_0_1_4_load_reg_801 <= LENET_C1_W_0_1_4_q0;
        LENET_C1_W_0_2_0_load_reg_806 <= LENET_C1_W_0_2_0_q0;
        LENET_C1_W_0_2_1_load_reg_811 <= LENET_C1_W_0_2_1_q0;
        LENET_C1_W_0_2_2_load_reg_816 <= LENET_C1_W_0_2_2_q0;
        LENET_C1_W_0_2_3_load_reg_821 <= LENET_C1_W_0_2_3_q0;
        LENET_C1_W_0_2_4_load_reg_826 <= LENET_C1_W_0_2_4_q0;
        LENET_C1_W_0_3_0_load_reg_831 <= LENET_C1_W_0_3_0_q0;
        LENET_C1_W_0_3_1_load_reg_836 <= LENET_C1_W_0_3_1_q0;
        LENET_C1_W_0_3_2_load_reg_841 <= LENET_C1_W_0_3_2_q0;
        LENET_C1_W_0_3_3_load_reg_846 <= LENET_C1_W_0_3_3_q0;
        LENET_C1_W_0_3_4_load_reg_851 <= LENET_C1_W_0_3_4_q0;
        LENET_C1_W_0_4_0_load_reg_856 <= LENET_C1_W_0_4_0_q0;
        LENET_C1_W_0_4_1_load_reg_861 <= LENET_C1_W_0_4_1_q0;
        LENET_C1_W_0_4_2_load_reg_866 <= LENET_C1_W_0_4_2_q0;
        LENET_C1_W_0_4_3_load_reg_871 <= LENET_C1_W_0_4_3_q0;
        LENET_C1_W_0_4_4_load_reg_876 <= LENET_C1_W_0_4_4_q0;
        acc_reg_751 <= acc_fu_590_p6;
        sub_ln131_reg_746[6 : 1] <= sub_ln131_fu_583_p2[6 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        oc_1_reg_611 <= oc_fu_116;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_0_0_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_0_1_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_0_2_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_0_3_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_0_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_0_4_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_0_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_1_0_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_1_1_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_1_2_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_1_3_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_1_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_1_4_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_1_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_2_0_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_2_1_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_2_2_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_2_3_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_2_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_2_4_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_2_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_3_0_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_3_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_3_1_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_3_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_3_2_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_3_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_3_3_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_3_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_3_4_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_3_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_4_0_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_4_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_4_1_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_4_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_4_2_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_4_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_4_3_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_4_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        LENET_C1_W_0_4_4_ce0 = 1'b1;
    end else begin
        LENET_C1_W_0_4_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln117_fu_515_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln117_fu_515_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln117_fu_515_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign LENET_C1_W_0_0_0_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_0_1_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_0_2_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_0_3_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_0_4_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_1_0_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_1_1_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_1_2_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_1_3_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_1_4_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_2_0_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_2_1_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_2_2_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_2_3_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_2_4_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_3_0_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_3_1_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_3_2_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_3_3_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_3_4_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_4_0_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_4_1_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_4_2_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_4_3_address0 = zext_ln117_fu_527_p1;

assign LENET_C1_W_0_4_4_address0 = zext_ln117_fu_527_p1;

assign add_ln117_fu_521_p2 = (oc_fu_116 + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start = grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start_reg;

assign icmp_ln117_fu_515_p2 = ((oc_fu_116 == 2'd3) ? 1'b1 : 1'b0);

assign sub_ln131_fu_583_p2 = (zext_ln131_fu_568_p1 - zext_ln131_3_fu_579_p1);

assign tmp_6_fu_572_p3 = {{oc_1_reg_611}, {1'd0}};

assign tmp_fu_561_p3 = {{oc_1_reg_611}, {4'd0}};

assign x_address0 = grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_address0;

assign x_address1 = grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_address1;

assign x_ce0 = grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_ce0;

assign x_ce1 = grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_ce1;

assign y_0_address1 = grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_address1;

assign y_0_ce1 = grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_ce1;

assign y_0_d1 = grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_d1;

assign y_0_we1 = grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_we1;

assign y_1_address1 = grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_address1;

assign y_1_ce1 = grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_ce1;

assign y_1_d1 = grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_d1;

assign y_1_we1 = grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_we1;

assign zext_ln117_fu_527_p1 = oc_fu_116;

assign zext_ln131_3_fu_579_p1 = tmp_6_fu_572_p3;

assign zext_ln131_fu_568_p1 = tmp_fu_561_p3;

always @ (posedge ap_clk) begin
    sub_ln131_reg_746[0] <= 1'b0;
end

endmodule //top_A_conv1_pragma
