// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_A_top_A,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.060000,HLS_SYN_LAT=18852,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1669,HLS_SYN_LUT=2564,HLS_VERSION=2023_1}" *)

module top_A (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_address0,
        x_ce0,
        x_q0,
        x_address1,
        x_ce1,
        x_q1,
        p1_address0,
        p1_ce0,
        p1_we0,
        p1_d0
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_pp0_stage0 = 5'd4;
parameter    ap_ST_fsm_pp0_stage1 = 5'd8;
parameter    ap_ST_fsm_state8 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] x_address0;
output   x_ce0;
input  [7:0] x_q0;
output  [9:0] x_address1;
output   x_ce1;
input  [7:0] x_q1;
output  [9:0] p1_address0;
output   p1_ce0;
output   p1_we0;
output  [7:0] p1_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p1_ce0;
reg p1_we0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln140_fu_321_p2;
reg   [0:0] icmp_ln140_reg_688;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state7_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln141_fu_336_p2;
reg   [0:0] icmp_ln141_reg_692;
wire   [3:0] select_ln141_fu_457_p3;
reg   [3:0] select_ln141_reg_700;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state4_pp0_stage1_iter0;
wire    ap_block_state6_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
wire   [7:0] add_ln150_fu_477_p2;
reg   [7:0] add_ln150_reg_706;
wire   [5:0] trunc_ln150_fu_483_p1;
reg   [5:0] trunc_ln150_reg_712;
wire   [9:0] add_ln150_1_fu_559_p2;
reg   [9:0] add_ln150_1_reg_718;
wire   [7:0] m1_fu_616_p3;
reg   [7:0] m1_reg_743;
wire   [7:0] m2_fu_630_p3;
reg   [7:0] m2_reg_749;
reg    ap_enable_reg_pp0_iter0;
wire    ap_CS_fsm_state2;
wire    grp_conv1_pragma_fu_233_ap_done;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter2;
wire   [10:0] y1_0_address0;
reg    y1_0_ce0;
wire   [7:0] y1_0_q0;
reg   [10:0] y1_0_address1;
reg    y1_0_ce1;
reg    y1_0_we1;
wire   [7:0] y1_0_q1;
wire   [10:0] y1_1_address0;
reg    y1_1_ce0;
wire   [7:0] y1_1_q0;
reg   [10:0] y1_1_address1;
reg    y1_1_ce1;
reg    y1_1_we1;
wire   [7:0] y1_1_q1;
wire    grp_conv1_pragma_fu_233_ap_start;
wire    grp_conv1_pragma_fu_233_ap_idle;
wire    grp_conv1_pragma_fu_233_ap_ready;
wire   [9:0] grp_conv1_pragma_fu_233_x_address0;
wire    grp_conv1_pragma_fu_233_x_ce0;
wire   [9:0] grp_conv1_pragma_fu_233_x_address1;
wire    grp_conv1_pragma_fu_233_x_ce1;
wire   [10:0] grp_conv1_pragma_fu_233_y_0_address1;
wire    grp_conv1_pragma_fu_233_y_0_ce1;
wire    grp_conv1_pragma_fu_233_y_0_we1;
wire   [7:0] grp_conv1_pragma_fu_233_y_0_d1;
wire   [10:0] grp_conv1_pragma_fu_233_y_1_address1;
wire    grp_conv1_pragma_fu_233_y_1_ce1;
wire    grp_conv1_pragma_fu_233_y_1_we1;
wire   [7:0] grp_conv1_pragma_fu_233_y_1_d1;
reg    grp_conv1_pragma_fu_233_ap_start_reg;
wire   [63:0] zext_ln146_1_fu_582_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln146_3_fu_604_p1;
wire   [63:0] zext_ln150_4_fu_638_p1;
reg   [3:0] ow_fu_146;
wire   [3:0] add_ln142_fu_487_p2;
wire    ap_block_pp0_stage1;
reg   [3:0] oh_fu_150;
wire   [3:0] select_ln141_1_fu_465_p3;
reg   [7:0] indvar_flatten_fu_154;
wire   [7:0] select_ln141_2_fu_348_p3;
reg   [1:0] c_fu_158;
wire   [1:0] select_ln140_1_fu_388_p3;
reg   [9:0] indvar_flatten14_fu_162;
wire   [9:0] add_ln140_1_fu_327_p2;
wire   [7:0] add_ln141_1_fu_342_p2;
wire   [1:0] add_ln140_fu_375_p2;
wire   [5:0] tmp_fu_395_p3;
wire   [2:0] tmp_1_fu_407_p3;
wire   [6:0] zext_ln150_fu_403_p1;
wire   [6:0] zext_ln150_1_fu_415_p1;
wire   [6:0] sub_ln150_fu_419_p2;
wire   [0:0] icmp_ln142_fu_434_p2;
wire   [0:0] xor_ln140_fu_429_p2;
wire   [3:0] select_ln140_fu_381_p3;
wire   [0:0] and_ln140_fu_440_p2;
wire   [0:0] or_ln141_fu_452_p2;
wire   [3:0] add_ln141_fu_446_p2;
wire  signed [7:0] sext_ln141_fu_425_p1;
wire   [7:0] zext_ln150_2_fu_473_p1;
wire   [8:0] tmp_2_fu_515_p3;
wire   [9:0] p_shl2_fu_508_p3;
wire  signed [9:0] sext_ln150_fu_522_p1;
wire   [9:0] tmp_3_fu_539_p3;
wire   [10:0] p_shl_fu_532_p3;
wire  signed [10:0] sext_ln146_fu_546_p1;
wire   [9:0] sub_ln150_1_fu_526_p2;
wire   [9:0] zext_ln150_3_fu_556_p1;
wire   [4:0] shl_ln_fu_565_p3;
wire   [10:0] sub_ln146_fu_550_p2;
wire   [10:0] zext_ln146_fu_572_p1;
wire   [10:0] add_ln146_fu_576_p2;
wire   [4:0] or_ln146_fu_588_p2;
wire   [10:0] zext_ln146_2_fu_594_p1;
wire   [10:0] add_ln146_1_fu_598_p2;
wire   [0:0] icmp_ln146_fu_610_p2;
wire   [0:0] icmp_ln148_fu_624_p2;
wire   [0:0] icmp_ln150_fu_642_p2;
wire    ap_CS_fsm_state8;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 grp_conv1_pragma_fu_233_ap_start_reg = 1'b0;
end

top_A_y1_0_RAM_2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1176 ),
    .AddressWidth( 11 ))
y1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(y1_0_address0),
    .ce0(y1_0_ce0),
    .q0(y1_0_q0),
    .address1(y1_0_address1),
    .ce1(y1_0_ce1),
    .we1(y1_0_we1),
    .d1(grp_conv1_pragma_fu_233_y_0_d1),
    .q1(y1_0_q1)
);

top_A_y1_0_RAM_2P_BRAM_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1176 ),
    .AddressWidth( 11 ))
y1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(y1_1_address0),
    .ce0(y1_1_ce0),
    .q0(y1_1_q0),
    .address1(y1_1_address1),
    .ce1(y1_1_ce1),
    .we1(y1_1_we1),
    .d1(grp_conv1_pragma_fu_233_y_1_d1),
    .q1(y1_1_q1)
);

top_A_conv1_pragma grp_conv1_pragma_fu_233(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv1_pragma_fu_233_ap_start),
    .ap_done(grp_conv1_pragma_fu_233_ap_done),
    .ap_idle(grp_conv1_pragma_fu_233_ap_idle),
    .ap_ready(grp_conv1_pragma_fu_233_ap_ready),
    .x_address0(grp_conv1_pragma_fu_233_x_address0),
    .x_ce0(grp_conv1_pragma_fu_233_x_ce0),
    .x_q0(x_q0),
    .x_address1(grp_conv1_pragma_fu_233_x_address1),
    .x_ce1(grp_conv1_pragma_fu_233_x_ce1),
    .x_q1(x_q1),
    .y_0_address1(grp_conv1_pragma_fu_233_y_0_address1),
    .y_0_ce1(grp_conv1_pragma_fu_233_y_0_ce1),
    .y_0_we1(grp_conv1_pragma_fu_233_y_0_we1),
    .y_0_d1(grp_conv1_pragma_fu_233_y_0_d1),
    .y_1_address1(grp_conv1_pragma_fu_233_y_1_address1),
    .y_1_ce1(grp_conv1_pragma_fu_233_y_1_ce1),
    .y_1_we1(grp_conv1_pragma_fu_233_y_1_we1),
    .y_1_d1(grp_conv1_pragma_fu_233_y_1_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (grp_conv1_pragma_fu_233_ap_done == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((1'b1 == ap_CS_fsm_state2) & (grp_conv1_pragma_fu_233_ap_done == 1'b1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv1_pragma_fu_233_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_conv1_pragma_fu_233_ap_start_reg <= 1'b1;
        end else if ((grp_conv1_pragma_fu_233_ap_ready == 1'b1)) begin
            grp_conv1_pragma_fu_233_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        c_fu_158 <= 2'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln140_reg_688 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        c_fu_158 <= select_ln140_1_fu_388_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten14_fu_162 <= 10'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln140_fu_321_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten14_fu_162 <= add_ln140_1_fu_327_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten_fu_154 <= 8'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln140_fu_321_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_fu_154 <= select_ln141_2_fu_348_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        oh_fu_150 <= 4'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln140_reg_688 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        oh_fu_150 <= select_ln141_1_fu_465_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        ow_fu_146 <= 4'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln140_reg_688 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ow_fu_146 <= add_ln142_fu_487_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln150_1_reg_718 <= add_ln150_1_fu_559_p2;
        icmp_ln140_reg_688 <= icmp_ln140_fu_321_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln140_reg_688 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln150_reg_706 <= add_ln150_fu_477_p2;
        select_ln141_reg_700 <= select_ln141_fu_457_p3;
        trunc_ln150_reg_712 <= trunc_ln150_fu_483_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln140_fu_321_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln141_reg_692 <= icmp_ln141_fu_336_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        m1_reg_743 <= m1_fu_616_p3;
        m2_reg_749 <= m2_fu_630_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_conv1_pragma_fu_233_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((icmp_ln140_fu_321_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p1_ce0 = 1'b1;
    end else begin
        p1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p1_we0 = 1'b1;
    end else begin
        p1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        y1_0_address1 = zext_ln146_1_fu_582_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        y1_0_address1 = grp_conv1_pragma_fu_233_y_0_address1;
    end else begin
        y1_0_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        y1_0_ce0 = 1'b1;
    end else begin
        y1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        y1_0_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        y1_0_ce1 = grp_conv1_pragma_fu_233_y_0_ce1;
    end else begin
        y1_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y1_0_we1 = grp_conv1_pragma_fu_233_y_0_we1;
    end else begin
        y1_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        y1_1_address1 = zext_ln146_1_fu_582_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        y1_1_address1 = grp_conv1_pragma_fu_233_y_1_address1;
    end else begin
        y1_1_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        y1_1_ce0 = 1'b1;
    end else begin
        y1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        y1_1_ce1 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        y1_1_ce1 = grp_conv1_pragma_fu_233_y_1_ce1;
    end else begin
        y1_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y1_1_we1 = grp_conv1_pragma_fu_233_y_1_we1;
    end else begin
        y1_1_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_conv1_pragma_fu_233_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln140_fu_321_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln140_fu_321_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln140_1_fu_327_p2 = (indvar_flatten14_fu_162 + 10'd1);

assign add_ln140_fu_375_p2 = (c_fu_158 + 2'd1);

assign add_ln141_1_fu_342_p2 = (indvar_flatten_fu_154 + 8'd1);

assign add_ln141_fu_446_p2 = (select_ln140_fu_381_p3 + 4'd1);

assign add_ln142_fu_487_p2 = (select_ln141_fu_457_p3 + 4'd1);

assign add_ln146_1_fu_598_p2 = (sub_ln146_fu_550_p2 + zext_ln146_2_fu_594_p1);

assign add_ln146_fu_576_p2 = (sub_ln146_fu_550_p2 + zext_ln146_fu_572_p1);

assign add_ln150_1_fu_559_p2 = (sub_ln150_1_fu_526_p2 + zext_ln150_3_fu_556_p1);

assign add_ln150_fu_477_p2 = ($signed(sext_ln141_fu_425_p1) + $signed(zext_ln150_2_fu_473_p1));

assign and_ln140_fu_440_p2 = (xor_ln140_fu_429_p2 & icmp_ln142_fu_434_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign grp_conv1_pragma_fu_233_ap_start = grp_conv1_pragma_fu_233_ap_start_reg;

assign icmp_ln140_fu_321_p2 = ((indvar_flatten14_fu_162 == 10'd588) ? 1'b1 : 1'b0);

assign icmp_ln141_fu_336_p2 = ((indvar_flatten_fu_154 == 8'd196) ? 1'b1 : 1'b0);

assign icmp_ln142_fu_434_p2 = ((ow_fu_146 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln146_fu_610_p2 = ((y1_0_q1 > y1_0_q0) ? 1'b1 : 1'b0);

assign icmp_ln148_fu_624_p2 = ((y1_1_q1 > y1_1_q0) ? 1'b1 : 1'b0);

assign icmp_ln150_fu_642_p2 = ((m1_reg_743 > m2_reg_749) ? 1'b1 : 1'b0);

assign m1_fu_616_p3 = ((icmp_ln146_fu_610_p2[0:0] == 1'b1) ? y1_0_q1 : y1_0_q0);

assign m2_fu_630_p3 = ((icmp_ln148_fu_624_p2[0:0] == 1'b1) ? y1_1_q1 : y1_1_q0);

assign or_ln141_fu_452_p2 = (icmp_ln141_reg_692 | and_ln140_fu_440_p2);

assign or_ln146_fu_588_p2 = (shl_ln_fu_565_p3 | 5'd1);

assign p1_address0 = zext_ln150_4_fu_638_p1;

assign p1_d0 = ((icmp_ln150_fu_642_p2[0:0] == 1'b1) ? m1_reg_743 : m2_reg_749);

assign p_shl2_fu_508_p3 = {{trunc_ln150_reg_712}, {4'd0}};

assign p_shl_fu_532_p3 = {{trunc_ln150_reg_712}, {5'd0}};

assign select_ln140_1_fu_388_p3 = ((icmp_ln141_reg_692[0:0] == 1'b1) ? add_ln140_fu_375_p2 : c_fu_158);

assign select_ln140_fu_381_p3 = ((icmp_ln141_reg_692[0:0] == 1'b1) ? 4'd0 : oh_fu_150);

assign select_ln141_1_fu_465_p3 = ((and_ln140_fu_440_p2[0:0] == 1'b1) ? add_ln141_fu_446_p2 : select_ln140_fu_381_p3);

assign select_ln141_2_fu_348_p3 = ((icmp_ln141_fu_336_p2[0:0] == 1'b1) ? 8'd1 : add_ln141_1_fu_342_p2);

assign select_ln141_fu_457_p3 = ((or_ln141_fu_452_p2[0:0] == 1'b1) ? 4'd0 : ow_fu_146);

assign sext_ln141_fu_425_p1 = $signed(sub_ln150_fu_419_p2);

assign sext_ln146_fu_546_p1 = $signed(tmp_3_fu_539_p3);

assign sext_ln150_fu_522_p1 = $signed(tmp_2_fu_515_p3);

assign shl_ln_fu_565_p3 = {{select_ln141_reg_700}, {1'd0}};

assign sub_ln146_fu_550_p2 = ($signed(p_shl_fu_532_p3) - $signed(sext_ln146_fu_546_p1));

assign sub_ln150_1_fu_526_p2 = ($signed(p_shl2_fu_508_p3) - $signed(sext_ln150_fu_522_p1));

assign sub_ln150_fu_419_p2 = (zext_ln150_fu_403_p1 - zext_ln150_1_fu_415_p1);

assign tmp_1_fu_407_p3 = {{select_ln140_1_fu_388_p3}, {1'd0}};

assign tmp_2_fu_515_p3 = {{add_ln150_reg_706}, {1'd0}};

assign tmp_3_fu_539_p3 = {{add_ln150_reg_706}, {2'd0}};

assign tmp_fu_395_p3 = {{select_ln140_1_fu_388_p3}, {4'd0}};

assign trunc_ln150_fu_483_p1 = add_ln150_fu_477_p2[5:0];

assign x_address0 = grp_conv1_pragma_fu_233_x_address0;

assign x_address1 = grp_conv1_pragma_fu_233_x_address1;

assign x_ce0 = grp_conv1_pragma_fu_233_x_ce0;

assign x_ce1 = grp_conv1_pragma_fu_233_x_ce1;

assign xor_ln140_fu_429_p2 = (icmp_ln141_reg_692 ^ 1'd1);

assign y1_0_address0 = zext_ln146_3_fu_604_p1;

assign y1_1_address0 = zext_ln146_3_fu_604_p1;

assign zext_ln146_1_fu_582_p1 = add_ln146_fu_576_p2;

assign zext_ln146_2_fu_594_p1 = or_ln146_fu_588_p2;

assign zext_ln146_3_fu_604_p1 = add_ln146_1_fu_598_p2;

assign zext_ln146_fu_572_p1 = shl_ln_fu_565_p3;

assign zext_ln150_1_fu_415_p1 = tmp_1_fu_407_p3;

assign zext_ln150_2_fu_473_p1 = select_ln141_1_fu_465_p3;

assign zext_ln150_3_fu_556_p1 = select_ln141_reg_700;

assign zext_ln150_4_fu_638_p1 = add_ln150_1_reg_718;

assign zext_ln150_fu_403_p1 = tmp_fu_395_p3;

endmodule //top_A
