-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_A is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_ce0 : OUT STD_LOGIC;
    x_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_ce1 : OUT STD_LOGIC;
    x_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p1_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    p1_ce0 : OUT STD_LOGIC;
    p1_we0 : OUT STD_LOGIC;
    p1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of top_A is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "top_A_top_A,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.060000,HLS_SYN_LAT=18852,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=1669,HLS_SYN_LUT=2564,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_24C : STD_LOGIC_VECTOR (9 downto 0) := "1001001100";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv8_C4 : STD_LOGIC_VECTOR (7 downto 0) := "11000100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln140_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln140_reg_688 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln141_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln141_reg_692 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln141_fu_457_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln141_reg_700 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_state4_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state6_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal add_ln150_fu_477_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln150_reg_706 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln150_fu_483_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln150_reg_712 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln150_1_fu_559_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln150_1_reg_718 : STD_LOGIC_VECTOR (9 downto 0);
    signal m1_fu_616_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal m1_reg_743 : STD_LOGIC_VECTOR (7 downto 0);
    signal m2_fu_630_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal m2_reg_749 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_conv1_pragma_fu_233_ap_done : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal y1_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal y1_0_ce0 : STD_LOGIC;
    signal y1_0_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal y1_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal y1_0_ce1 : STD_LOGIC;
    signal y1_0_we1 : STD_LOGIC;
    signal y1_0_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal y1_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal y1_1_ce0 : STD_LOGIC;
    signal y1_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal y1_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal y1_1_ce1 : STD_LOGIC;
    signal y1_1_we1 : STD_LOGIC;
    signal y1_1_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv1_pragma_fu_233_ap_start : STD_LOGIC;
    signal grp_conv1_pragma_fu_233_ap_idle : STD_LOGIC;
    signal grp_conv1_pragma_fu_233_ap_ready : STD_LOGIC;
    signal grp_conv1_pragma_fu_233_x_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_conv1_pragma_fu_233_x_ce0 : STD_LOGIC;
    signal grp_conv1_pragma_fu_233_x_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_conv1_pragma_fu_233_x_ce1 : STD_LOGIC;
    signal grp_conv1_pragma_fu_233_y_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_conv1_pragma_fu_233_y_0_ce1 : STD_LOGIC;
    signal grp_conv1_pragma_fu_233_y_0_we1 : STD_LOGIC;
    signal grp_conv1_pragma_fu_233_y_0_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv1_pragma_fu_233_y_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_conv1_pragma_fu_233_y_1_ce1 : STD_LOGIC;
    signal grp_conv1_pragma_fu_233_y_1_we1 : STD_LOGIC;
    signal grp_conv1_pragma_fu_233_y_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv1_pragma_fu_233_ap_start_reg : STD_LOGIC := '0';
    signal zext_ln146_1_fu_582_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln146_3_fu_604_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln150_4_fu_638_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ow_fu_146 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln142_fu_487_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal oh_fu_150 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln141_1_fu_465_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_fu_154 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln141_2_fu_348_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal c_fu_158 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln140_1_fu_388_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten14_fu_162 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln140_1_fu_327_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln141_1_fu_342_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln140_fu_375_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_395_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_1_fu_407_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln150_fu_403_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln150_1_fu_415_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln150_fu_419_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln142_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln140_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln140_fu_381_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln140_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln141_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln141_fu_446_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln141_fu_425_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln150_2_fu_473_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_515_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl2_fu_508_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln150_fu_522_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_3_fu_539_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl_fu_532_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln146_fu_546_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln150_1_fu_526_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln150_3_fu_556_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_ln_fu_565_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln146_fu_550_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln146_fu_572_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln146_fu_576_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal or_ln146_fu_588_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln146_2_fu_594_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln146_1_fu_598_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln146_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln148_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln150_fu_642_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_A_conv1_pragma IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        x_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        x_ce0 : OUT STD_LOGIC;
        x_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        x_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        x_ce1 : OUT STD_LOGIC;
        x_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        y_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        y_0_ce1 : OUT STD_LOGIC;
        y_0_we1 : OUT STD_LOGIC;
        y_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        y_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        y_1_ce1 : OUT STD_LOGIC;
        y_1_we1 : OUT STD_LOGIC;
        y_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_y1_0_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0);
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    y1_0_U : component top_A_y1_0_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 1176,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => y1_0_address0,
        ce0 => y1_0_ce0,
        q0 => y1_0_q0,
        address1 => y1_0_address1,
        ce1 => y1_0_ce1,
        we1 => y1_0_we1,
        d1 => grp_conv1_pragma_fu_233_y_0_d1,
        q1 => y1_0_q1);

    y1_1_U : component top_A_y1_0_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 1176,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => y1_1_address0,
        ce0 => y1_1_ce0,
        q0 => y1_1_q0,
        address1 => y1_1_address1,
        ce1 => y1_1_ce1,
        we1 => y1_1_we1,
        d1 => grp_conv1_pragma_fu_233_y_1_d1,
        q1 => y1_1_q1);

    grp_conv1_pragma_fu_233 : component top_A_conv1_pragma
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_conv1_pragma_fu_233_ap_start,
        ap_done => grp_conv1_pragma_fu_233_ap_done,
        ap_idle => grp_conv1_pragma_fu_233_ap_idle,
        ap_ready => grp_conv1_pragma_fu_233_ap_ready,
        x_address0 => grp_conv1_pragma_fu_233_x_address0,
        x_ce0 => grp_conv1_pragma_fu_233_x_ce0,
        x_q0 => x_q0,
        x_address1 => grp_conv1_pragma_fu_233_x_address1,
        x_ce1 => grp_conv1_pragma_fu_233_x_ce1,
        x_q1 => x_q1,
        y_0_address1 => grp_conv1_pragma_fu_233_y_0_address1,
        y_0_ce1 => grp_conv1_pragma_fu_233_y_0_ce1,
        y_0_we1 => grp_conv1_pragma_fu_233_y_0_we1,
        y_0_d1 => grp_conv1_pragma_fu_233_y_0_d1,
        y_1_address1 => grp_conv1_pragma_fu_233_y_1_address1,
        y_1_ce1 => grp_conv1_pragma_fu_233_y_1_ce1,
        y_1_we1 => grp_conv1_pragma_fu_233_y_1_we1,
        y_1_d1 => grp_conv1_pragma_fu_233_y_1_d1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_conv1_pragma_fu_233_ap_done = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_conv1_pragma_fu_233_ap_done = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_conv1_pragma_fu_233_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_conv1_pragma_fu_233_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_conv1_pragma_fu_233_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv1_pragma_fu_233_ap_ready = ap_const_logic_1)) then 
                    grp_conv1_pragma_fu_233_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    c_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                c_fu_158 <= ap_const_lv2_0;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln140_reg_688 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                c_fu_158 <= select_ln140_1_fu_388_p3;
            end if; 
        end if;
    end process;

    indvar_flatten14_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten14_fu_162 <= ap_const_lv10_0;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln140_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten14_fu_162 <= add_ln140_1_fu_327_p2;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten_fu_154 <= ap_const_lv8_0;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln140_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                indvar_flatten_fu_154 <= select_ln141_2_fu_348_p3;
            end if; 
        end if;
    end process;

    oh_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                oh_fu_150 <= ap_const_lv4_0;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln140_reg_688 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                oh_fu_150 <= select_ln141_1_fu_465_p3;
            end if; 
        end if;
    end process;

    ow_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                ow_fu_146 <= ap_const_lv4_0;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln140_reg_688 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                ow_fu_146 <= add_ln142_fu_487_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln150_1_reg_718 <= add_ln150_1_fu_559_p2;
                icmp_ln140_reg_688 <= icmp_ln140_fu_321_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln140_reg_688 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                add_ln150_reg_706 <= add_ln150_fu_477_p2;
                select_ln141_reg_700 <= select_ln141_fu_457_p3;
                trunc_ln150_reg_712 <= trunc_ln150_fu_483_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln140_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln141_reg_692 <= icmp_ln141_fu_336_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                m1_reg_743 <= m1_fu_616_p3;
                m2_reg_749 <= m2_fu_630_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln140_fu_321_p2, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_CS_fsm_state2, grp_conv1_pragma_fu_233_ap_done, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_conv1_pragma_fu_233_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln140_fu_321_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln140_fu_321_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln140_1_fu_327_p2 <= std_logic_vector(unsigned(indvar_flatten14_fu_162) + unsigned(ap_const_lv10_1));
    add_ln140_fu_375_p2 <= std_logic_vector(unsigned(c_fu_158) + unsigned(ap_const_lv2_1));
    add_ln141_1_fu_342_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_154) + unsigned(ap_const_lv8_1));
    add_ln141_fu_446_p2 <= std_logic_vector(unsigned(select_ln140_fu_381_p3) + unsigned(ap_const_lv4_1));
    add_ln142_fu_487_p2 <= std_logic_vector(unsigned(select_ln141_fu_457_p3) + unsigned(ap_const_lv4_1));
    add_ln146_1_fu_598_p2 <= std_logic_vector(unsigned(sub_ln146_fu_550_p2) + unsigned(zext_ln146_2_fu_594_p1));
    add_ln146_fu_576_p2 <= std_logic_vector(unsigned(sub_ln146_fu_550_p2) + unsigned(zext_ln146_fu_572_p1));
    add_ln150_1_fu_559_p2 <= std_logic_vector(unsigned(sub_ln150_1_fu_526_p2) + unsigned(zext_ln150_3_fu_556_p1));
    add_ln150_fu_477_p2 <= std_logic_vector(signed(sext_ln141_fu_425_p1) + signed(zext_ln150_2_fu_473_p1));
    and_ln140_fu_440_p2 <= (xor_ln140_fu_429_p2 and icmp_ln142_fu_434_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state8 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_conv1_pragma_fu_233_ap_done)
    begin
        if ((grp_conv1_pragma_fu_233_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage1_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state3_assign_proc : process(icmp_ln140_fu_321_p2)
    begin
        if ((icmp_ln140_fu_321_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_conv1_pragma_fu_233_ap_start <= grp_conv1_pragma_fu_233_ap_start_reg;
    icmp_ln140_fu_321_p2 <= "1" when (indvar_flatten14_fu_162 = ap_const_lv10_24C) else "0";
    icmp_ln141_fu_336_p2 <= "1" when (indvar_flatten_fu_154 = ap_const_lv8_C4) else "0";
    icmp_ln142_fu_434_p2 <= "1" when (ow_fu_146 = ap_const_lv4_E) else "0";
    icmp_ln146_fu_610_p2 <= "1" when (unsigned(y1_0_q1) > unsigned(y1_0_q0)) else "0";
    icmp_ln148_fu_624_p2 <= "1" when (unsigned(y1_1_q1) > unsigned(y1_1_q0)) else "0";
    icmp_ln150_fu_642_p2 <= "1" when (unsigned(m1_reg_743) > unsigned(m2_reg_749)) else "0";
    m1_fu_616_p3 <= 
        y1_0_q1 when (icmp_ln146_fu_610_p2(0) = '1') else 
        y1_0_q0;
    m2_fu_630_p3 <= 
        y1_1_q1 when (icmp_ln148_fu_624_p2(0) = '1') else 
        y1_1_q0;
    or_ln141_fu_452_p2 <= (icmp_ln141_reg_692 or and_ln140_fu_440_p2);
    or_ln146_fu_588_p2 <= (shl_ln_fu_565_p3 or ap_const_lv5_1);
    p1_address0 <= zext_ln150_4_fu_638_p1(10 - 1 downto 0);

    p1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p1_ce0 <= ap_const_logic_1;
        else 
            p1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p1_d0 <= 
        m1_reg_743 when (icmp_ln150_fu_642_p2(0) = '1') else 
        m2_reg_749;

    p1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            p1_we0 <= ap_const_logic_1;
        else 
            p1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_shl2_fu_508_p3 <= (trunc_ln150_reg_712 & ap_const_lv4_0);
    p_shl_fu_532_p3 <= (trunc_ln150_reg_712 & ap_const_lv5_0);
    select_ln140_1_fu_388_p3 <= 
        add_ln140_fu_375_p2 when (icmp_ln141_reg_692(0) = '1') else 
        c_fu_158;
    select_ln140_fu_381_p3 <= 
        ap_const_lv4_0 when (icmp_ln141_reg_692(0) = '1') else 
        oh_fu_150;
    select_ln141_1_fu_465_p3 <= 
        add_ln141_fu_446_p2 when (and_ln140_fu_440_p2(0) = '1') else 
        select_ln140_fu_381_p3;
    select_ln141_2_fu_348_p3 <= 
        ap_const_lv8_1 when (icmp_ln141_fu_336_p2(0) = '1') else 
        add_ln141_1_fu_342_p2;
    select_ln141_fu_457_p3 <= 
        ap_const_lv4_0 when (or_ln141_fu_452_p2(0) = '1') else 
        ow_fu_146;
        sext_ln141_fu_425_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln150_fu_419_p2),8));

        sext_ln146_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_3_fu_539_p3),11));

        sext_ln150_fu_522_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_515_p3),10));

    shl_ln_fu_565_p3 <= (select_ln141_reg_700 & ap_const_lv1_0);
    sub_ln146_fu_550_p2 <= std_logic_vector(unsigned(p_shl_fu_532_p3) - unsigned(sext_ln146_fu_546_p1));
    sub_ln150_1_fu_526_p2 <= std_logic_vector(unsigned(p_shl2_fu_508_p3) - unsigned(sext_ln150_fu_522_p1));
    sub_ln150_fu_419_p2 <= std_logic_vector(unsigned(zext_ln150_fu_403_p1) - unsigned(zext_ln150_1_fu_415_p1));
    tmp_1_fu_407_p3 <= (select_ln140_1_fu_388_p3 & ap_const_lv1_0);
    tmp_2_fu_515_p3 <= (add_ln150_reg_706 & ap_const_lv1_0);
    tmp_3_fu_539_p3 <= (add_ln150_reg_706 & ap_const_lv2_0);
    tmp_fu_395_p3 <= (select_ln140_1_fu_388_p3 & ap_const_lv4_0);
    trunc_ln150_fu_483_p1 <= add_ln150_fu_477_p2(6 - 1 downto 0);
    x_address0 <= grp_conv1_pragma_fu_233_x_address0;
    x_address1 <= grp_conv1_pragma_fu_233_x_address1;
    x_ce0 <= grp_conv1_pragma_fu_233_x_ce0;
    x_ce1 <= grp_conv1_pragma_fu_233_x_ce1;
    xor_ln140_fu_429_p2 <= (icmp_ln141_reg_692 xor ap_const_lv1_1);
    y1_0_address0 <= zext_ln146_3_fu_604_p1(11 - 1 downto 0);

    y1_0_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_state2, ap_enable_reg_pp0_iter1, grp_conv1_pragma_fu_233_y_0_address1, zext_ln146_1_fu_582_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            y1_0_address1 <= zext_ln146_1_fu_582_p1(11 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            y1_0_address1 <= grp_conv1_pragma_fu_233_y_0_address1;
        else 
            y1_0_address1 <= "XXXXXXXXXXX";
        end if; 
    end process;


    y1_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            y1_0_ce0 <= ap_const_logic_1;
        else 
            y1_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    y1_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_CS_fsm_state2, ap_enable_reg_pp0_iter1, grp_conv1_pragma_fu_233_y_0_ce1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            y1_0_ce1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            y1_0_ce1 <= grp_conv1_pragma_fu_233_y_0_ce1;
        else 
            y1_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    y1_0_we1_assign_proc : process(ap_CS_fsm_state2, grp_conv1_pragma_fu_233_y_0_we1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            y1_0_we1 <= grp_conv1_pragma_fu_233_y_0_we1;
        else 
            y1_0_we1 <= ap_const_logic_0;
        end if; 
    end process;

    y1_1_address0 <= zext_ln146_3_fu_604_p1(11 - 1 downto 0);

    y1_1_address1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_state2, ap_enable_reg_pp0_iter1, grp_conv1_pragma_fu_233_y_1_address1, zext_ln146_1_fu_582_p1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            y1_1_address1 <= zext_ln146_1_fu_582_p1(11 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            y1_1_address1 <= grp_conv1_pragma_fu_233_y_1_address1;
        else 
            y1_1_address1 <= "XXXXXXXXXXX";
        end if; 
    end process;


    y1_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            y1_1_ce0 <= ap_const_logic_1;
        else 
            y1_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    y1_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_CS_fsm_state2, ap_enable_reg_pp0_iter1, grp_conv1_pragma_fu_233_y_1_ce1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
            y1_1_ce1 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            y1_1_ce1 <= grp_conv1_pragma_fu_233_y_1_ce1;
        else 
            y1_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    y1_1_we1_assign_proc : process(ap_CS_fsm_state2, grp_conv1_pragma_fu_233_y_1_we1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            y1_1_we1 <= grp_conv1_pragma_fu_233_y_1_we1;
        else 
            y1_1_we1 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln146_1_fu_582_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln146_fu_576_p2),64));
    zext_ln146_2_fu_594_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln146_fu_588_p2),11));
    zext_ln146_3_fu_604_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln146_1_fu_598_p2),64));
    zext_ln146_fu_572_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_565_p3),11));
    zext_ln150_1_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_407_p3),7));
    zext_ln150_2_fu_473_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln141_1_fu_465_p3),8));
    zext_ln150_3_fu_556_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln141_reg_700),10));
    zext_ln150_4_fu_638_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln150_1_reg_718),64));
    zext_ln150_fu_403_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_395_p3),7));
end behav;
