-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_A_conv1_pragma is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_ce0 : OUT STD_LOGIC;
    x_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    x_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    x_ce1 : OUT STD_LOGIC;
    x_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
    y_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    y_0_ce1 : OUT STD_LOGIC;
    y_0_we1 : OUT STD_LOGIC;
    y_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    y_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    y_1_ce1 : OUT STD_LOGIC;
    y_1_we1 : OUT STD_LOGIC;
    y_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of top_A_conv1_pragma is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv15_DEB : STD_LOGIC_VECTOR (14 downto 0) := "000110111101011";
    constant ap_const_lv15_7F2F : STD_LOGIC_VECTOR (14 downto 0) := "111111100101111";
    constant ap_const_lv15_5AE2 : STD_LOGIC_VECTOR (14 downto 0) := "101101011100010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal LENET_C1_W_0_0_0_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_0_0_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_0_0_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_0_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_0_1_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_0_1_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_0_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_0_2_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_0_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_0_3_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_0_3_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_0_3_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_0_4_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_0_4_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_0_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_1_0_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_1_0_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_1_0_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_1_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_1_1_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_1_1_q0 : STD_LOGIC_VECTOR (5 downto 0);
    signal LENET_C1_W_0_1_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_1_2_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_1_2_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_1_3_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_1_3_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_1_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_1_4_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_1_4_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_1_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_2_0_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_2_0_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_2_0_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_2_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_2_1_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_2_1_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_2_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_2_2_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_2_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_2_3_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_2_3_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_2_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_2_4_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_2_4_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_2_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_3_0_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_3_0_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_3_0_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_3_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_3_1_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_3_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_3_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_3_2_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_3_2_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_3_3_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_3_3_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_3_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_3_4_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_3_4_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_3_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_4_0_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_4_0_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_4_0_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_4_1_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_4_1_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_4_1_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_4_2_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_4_2_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_4_2_q0 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_4_3_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_4_3_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_4_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_4_4_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal LENET_C1_W_0_4_4_ce0 : STD_LOGIC;
    signal LENET_C1_W_0_4_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal oc_1_reg_611 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln117_fu_515_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln131_fu_583_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal sub_ln131_reg_746 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal acc_fu_590_p6 : STD_LOGIC_VECTOR (14 downto 0);
    signal acc_reg_751 : STD_LOGIC_VECTOR (14 downto 0);
    signal LENET_C1_W_0_0_0_load_reg_756 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_0_1_load_reg_761 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_0_2_load_reg_766 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_0_3_load_reg_771 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_0_4_load_reg_776 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_1_0_load_reg_781 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_1_1_load_reg_786 : STD_LOGIC_VECTOR (5 downto 0);
    signal LENET_C1_W_0_1_2_load_reg_791 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_1_3_load_reg_796 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_1_4_load_reg_801 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_2_0_load_reg_806 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_2_1_load_reg_811 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_2_2_load_reg_816 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_2_3_load_reg_821 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_2_4_load_reg_826 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_3_0_load_reg_831 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_3_1_load_reg_836 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_3_2_load_reg_841 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_3_3_load_reg_846 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_3_4_load_reg_851 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_4_0_load_reg_856 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_4_1_load_reg_861 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_4_2_load_reg_866 : STD_LOGIC_VECTOR (6 downto 0);
    signal LENET_C1_W_0_4_3_load_reg_871 : STD_LOGIC_VECTOR (7 downto 0);
    signal LENET_C1_W_0_4_4_load_reg_876 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start : STD_LOGIC;
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_done : STD_LOGIC;
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_idle : STD_LOGIC;
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_ready : STD_LOGIC;
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_ce0 : STD_LOGIC;
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_ce1 : STD_LOGIC;
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_ce1 : STD_LOGIC;
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_we1 : STD_LOGIC;
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_ce1 : STD_LOGIC;
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_we1 : STD_LOGIC;
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal zext_ln117_fu_527_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal oc_fu_116 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln117_fu_521_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_561_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_6_fu_572_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln131_fu_568_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln131_3_fu_579_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_A_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sub_ln131 : IN STD_LOGIC_VECTOR (6 downto 0);
        x_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        x_ce0 : OUT STD_LOGIC;
        x_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        x_address1 : OUT STD_LOGIC_VECTOR (9 downto 0);
        x_ce1 : OUT STD_LOGIC;
        x_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        y_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        y_0_ce1 : OUT STD_LOGIC;
        y_0_we1 : OUT STD_LOGIC;
        y_0_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        y_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        y_1_ce1 : OUT STD_LOGIC;
        y_1_we1 : OUT STD_LOGIC;
        y_1_d1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_4_0_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_2_3_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_4_2_load_cast : IN STD_LOGIC_VECTOR (6 downto 0);
        LENET_C1_W_0_1_2_load_cast : IN STD_LOGIC_VECTOR (6 downto 0);
        LENET_C1_W_0_1_3_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_2_2_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_3_3_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_1_1_load_cast : IN STD_LOGIC_VECTOR (5 downto 0);
        LENET_C1_W_0_0_0_load_cast : IN STD_LOGIC_VECTOR (6 downto 0);
        LENET_C1_W_0_1_4_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_4_3_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_2_1_load_cast : IN STD_LOGIC_VECTOR (6 downto 0);
        LENET_C1_W_0_1_0_load_cast : IN STD_LOGIC_VECTOR (6 downto 0);
        LENET_C1_W_0_4_1_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_0_1_load_cast : IN STD_LOGIC_VECTOR (6 downto 0);
        LENET_C1_W_0_0_4_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_3_4_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_0_3_load_cast : IN STD_LOGIC_VECTOR (6 downto 0);
        LENET_C1_W_0_2_0_load_cast : IN STD_LOGIC_VECTOR (6 downto 0);
        LENET_C1_W_0_3_0_load_cast : IN STD_LOGIC_VECTOR (6 downto 0);
        LENET_C1_W_0_3_1_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_2_4_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_0_2_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        LENET_C1_W_0_3_2_load_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        sext_ln118 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_i_cast : IN STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component top_A_mux_4_2_15_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (14 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (14 downto 0);
        din3 : IN STD_LOGIC_VECTOR (14 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_0_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_0_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_0_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_0_3_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_0_4_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_1_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_1_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_1_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_1_3_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_1_4_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_2_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_2_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_2_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_2_3_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_2_4_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_3_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_3_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_3_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_3_3_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_3_4_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_4_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_4_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_4_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_4_3_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component top_A_conv1_pragma_LENET_C1_W_0_4_4_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    LENET_C1_W_0_0_0_U : component top_A_conv1_pragma_LENET_C1_W_0_0_0_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_0_0_address0,
        ce0 => LENET_C1_W_0_0_0_ce0,
        q0 => LENET_C1_W_0_0_0_q0);

    LENET_C1_W_0_0_1_U : component top_A_conv1_pragma_LENET_C1_W_0_0_1_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_0_1_address0,
        ce0 => LENET_C1_W_0_0_1_ce0,
        q0 => LENET_C1_W_0_0_1_q0);

    LENET_C1_W_0_0_2_U : component top_A_conv1_pragma_LENET_C1_W_0_0_2_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_0_2_address0,
        ce0 => LENET_C1_W_0_0_2_ce0,
        q0 => LENET_C1_W_0_0_2_q0);

    LENET_C1_W_0_0_3_U : component top_A_conv1_pragma_LENET_C1_W_0_0_3_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_0_3_address0,
        ce0 => LENET_C1_W_0_0_3_ce0,
        q0 => LENET_C1_W_0_0_3_q0);

    LENET_C1_W_0_0_4_U : component top_A_conv1_pragma_LENET_C1_W_0_0_4_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_0_4_address0,
        ce0 => LENET_C1_W_0_0_4_ce0,
        q0 => LENET_C1_W_0_0_4_q0);

    LENET_C1_W_0_1_0_U : component top_A_conv1_pragma_LENET_C1_W_0_1_0_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_1_0_address0,
        ce0 => LENET_C1_W_0_1_0_ce0,
        q0 => LENET_C1_W_0_1_0_q0);

    LENET_C1_W_0_1_1_U : component top_A_conv1_pragma_LENET_C1_W_0_1_1_ROM_AUTO_1R
    generic map (
        DataWidth => 6,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_1_1_address0,
        ce0 => LENET_C1_W_0_1_1_ce0,
        q0 => LENET_C1_W_0_1_1_q0);

    LENET_C1_W_0_1_2_U : component top_A_conv1_pragma_LENET_C1_W_0_1_2_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_1_2_address0,
        ce0 => LENET_C1_W_0_1_2_ce0,
        q0 => LENET_C1_W_0_1_2_q0);

    LENET_C1_W_0_1_3_U : component top_A_conv1_pragma_LENET_C1_W_0_1_3_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_1_3_address0,
        ce0 => LENET_C1_W_0_1_3_ce0,
        q0 => LENET_C1_W_0_1_3_q0);

    LENET_C1_W_0_1_4_U : component top_A_conv1_pragma_LENET_C1_W_0_1_4_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_1_4_address0,
        ce0 => LENET_C1_W_0_1_4_ce0,
        q0 => LENET_C1_W_0_1_4_q0);

    LENET_C1_W_0_2_0_U : component top_A_conv1_pragma_LENET_C1_W_0_2_0_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_2_0_address0,
        ce0 => LENET_C1_W_0_2_0_ce0,
        q0 => LENET_C1_W_0_2_0_q0);

    LENET_C1_W_0_2_1_U : component top_A_conv1_pragma_LENET_C1_W_0_2_1_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_2_1_address0,
        ce0 => LENET_C1_W_0_2_1_ce0,
        q0 => LENET_C1_W_0_2_1_q0);

    LENET_C1_W_0_2_2_U : component top_A_conv1_pragma_LENET_C1_W_0_2_2_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_2_2_address0,
        ce0 => LENET_C1_W_0_2_2_ce0,
        q0 => LENET_C1_W_0_2_2_q0);

    LENET_C1_W_0_2_3_U : component top_A_conv1_pragma_LENET_C1_W_0_2_3_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_2_3_address0,
        ce0 => LENET_C1_W_0_2_3_ce0,
        q0 => LENET_C1_W_0_2_3_q0);

    LENET_C1_W_0_2_4_U : component top_A_conv1_pragma_LENET_C1_W_0_2_4_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_2_4_address0,
        ce0 => LENET_C1_W_0_2_4_ce0,
        q0 => LENET_C1_W_0_2_4_q0);

    LENET_C1_W_0_3_0_U : component top_A_conv1_pragma_LENET_C1_W_0_3_0_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_3_0_address0,
        ce0 => LENET_C1_W_0_3_0_ce0,
        q0 => LENET_C1_W_0_3_0_q0);

    LENET_C1_W_0_3_1_U : component top_A_conv1_pragma_LENET_C1_W_0_3_1_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_3_1_address0,
        ce0 => LENET_C1_W_0_3_1_ce0,
        q0 => LENET_C1_W_0_3_1_q0);

    LENET_C1_W_0_3_2_U : component top_A_conv1_pragma_LENET_C1_W_0_3_2_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_3_2_address0,
        ce0 => LENET_C1_W_0_3_2_ce0,
        q0 => LENET_C1_W_0_3_2_q0);

    LENET_C1_W_0_3_3_U : component top_A_conv1_pragma_LENET_C1_W_0_3_3_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_3_3_address0,
        ce0 => LENET_C1_W_0_3_3_ce0,
        q0 => LENET_C1_W_0_3_3_q0);

    LENET_C1_W_0_3_4_U : component top_A_conv1_pragma_LENET_C1_W_0_3_4_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_3_4_address0,
        ce0 => LENET_C1_W_0_3_4_ce0,
        q0 => LENET_C1_W_0_3_4_q0);

    LENET_C1_W_0_4_0_U : component top_A_conv1_pragma_LENET_C1_W_0_4_0_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_4_0_address0,
        ce0 => LENET_C1_W_0_4_0_ce0,
        q0 => LENET_C1_W_0_4_0_q0);

    LENET_C1_W_0_4_1_U : component top_A_conv1_pragma_LENET_C1_W_0_4_1_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_4_1_address0,
        ce0 => LENET_C1_W_0_4_1_ce0,
        q0 => LENET_C1_W_0_4_1_q0);

    LENET_C1_W_0_4_2_U : component top_A_conv1_pragma_LENET_C1_W_0_4_2_ROM_AUTO_1R
    generic map (
        DataWidth => 7,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_4_2_address0,
        ce0 => LENET_C1_W_0_4_2_ce0,
        q0 => LENET_C1_W_0_4_2_q0);

    LENET_C1_W_0_4_3_U : component top_A_conv1_pragma_LENET_C1_W_0_4_3_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_4_3_address0,
        ce0 => LENET_C1_W_0_4_3_ce0,
        q0 => LENET_C1_W_0_4_3_q0);

    LENET_C1_W_0_4_4_U : component top_A_conv1_pragma_LENET_C1_W_0_4_4_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => LENET_C1_W_0_4_4_address0,
        ce0 => LENET_C1_W_0_4_4_ce0,
        q0 => LENET_C1_W_0_4_4_q0);

    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445 : component top_A_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start,
        ap_done => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_done,
        ap_idle => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_idle,
        ap_ready => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_ready,
        sub_ln131 => sub_ln131_reg_746,
        x_address0 => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_address0,
        x_ce0 => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_ce0,
        x_q0 => x_q0,
        x_address1 => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_address1,
        x_ce1 => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_ce1,
        x_q1 => x_q1,
        y_0_address1 => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_address1,
        y_0_ce1 => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_ce1,
        y_0_we1 => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_we1,
        y_0_d1 => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_d1,
        y_1_address1 => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_address1,
        y_1_ce1 => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_ce1,
        y_1_we1 => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_we1,
        y_1_d1 => grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_d1,
        LENET_C1_W_0_4_0_load_cast => LENET_C1_W_0_4_0_load_reg_856,
        LENET_C1_W_0_2_3_load_cast => LENET_C1_W_0_2_3_load_reg_821,
        LENET_C1_W_0_4_2_load_cast => LENET_C1_W_0_4_2_load_reg_866,
        LENET_C1_W_0_1_2_load_cast => LENET_C1_W_0_1_2_load_reg_791,
        LENET_C1_W_0_1_3_load_cast => LENET_C1_W_0_1_3_load_reg_796,
        LENET_C1_W_0_2_2_load_cast => LENET_C1_W_0_2_2_load_reg_816,
        LENET_C1_W_0_3_3_load_cast => LENET_C1_W_0_3_3_load_reg_846,
        LENET_C1_W_0_1_1_load_cast => LENET_C1_W_0_1_1_load_reg_786,
        LENET_C1_W_0_0_0_load_cast => LENET_C1_W_0_0_0_load_reg_756,
        LENET_C1_W_0_1_4_load_cast => LENET_C1_W_0_1_4_load_reg_801,
        LENET_C1_W_0_4_3_load_cast => LENET_C1_W_0_4_3_load_reg_871,
        LENET_C1_W_0_2_1_load_cast => LENET_C1_W_0_2_1_load_reg_811,
        LENET_C1_W_0_1_0_load_cast => LENET_C1_W_0_1_0_load_reg_781,
        LENET_C1_W_0_4_1_load_cast => LENET_C1_W_0_4_1_load_reg_861,
        LENET_C1_W_0_0_1_load_cast => LENET_C1_W_0_0_1_load_reg_761,
        LENET_C1_W_0_0_4_load_cast => LENET_C1_W_0_0_4_load_reg_776,
        LENET_C1_W_0_3_4_load_cast => LENET_C1_W_0_3_4_load_reg_851,
        LENET_C1_W_0_0_3_load_cast => LENET_C1_W_0_0_3_load_reg_771,
        LENET_C1_W_0_2_0_load_cast => LENET_C1_W_0_2_0_load_reg_806,
        LENET_C1_W_0_3_0_load_cast => LENET_C1_W_0_3_0_load_reg_831,
        LENET_C1_W_0_3_1_load_cast => LENET_C1_W_0_3_1_load_reg_836,
        LENET_C1_W_0_2_4_load_cast => LENET_C1_W_0_2_4_load_reg_826,
        LENET_C1_W_0_0_2_load_cast => LENET_C1_W_0_0_2_load_reg_766,
        LENET_C1_W_0_3_2_load_cast => LENET_C1_W_0_3_2_load_reg_841,
        sext_ln118 => LENET_C1_W_0_4_4_load_reg_876,
        merge_i_cast => acc_reg_751);

    mux_4_2_15_1_1_U96 : component top_A_mux_4_2_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 15,
        din1_WIDTH => 15,
        din2_WIDTH => 15,
        din3_WIDTH => 15,
        din4_WIDTH => 2,
        dout_WIDTH => 15)
    port map (
        din0 => ap_const_lv15_DEB,
        din1 => ap_const_lv15_7F2F,
        din2 => ap_const_lv15_5AE2,
        din3 => ap_const_lv15_5AE2,
        din4 => oc_1_reg_611,
        dout => acc_fu_590_p6);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_ready = ap_const_logic_1)) then 
                    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    oc_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                oc_fu_116 <= ap_const_lv2_0;
            elsif (((icmp_ln117_fu_515_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                oc_fu_116 <= add_ln117_fu_521_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                LENET_C1_W_0_0_0_load_reg_756 <= LENET_C1_W_0_0_0_q0;
                LENET_C1_W_0_0_1_load_reg_761 <= LENET_C1_W_0_0_1_q0;
                LENET_C1_W_0_0_2_load_reg_766 <= LENET_C1_W_0_0_2_q0;
                LENET_C1_W_0_0_3_load_reg_771 <= LENET_C1_W_0_0_3_q0;
                LENET_C1_W_0_0_4_load_reg_776 <= LENET_C1_W_0_0_4_q0;
                LENET_C1_W_0_1_0_load_reg_781 <= LENET_C1_W_0_1_0_q0;
                LENET_C1_W_0_1_1_load_reg_786 <= LENET_C1_W_0_1_1_q0;
                LENET_C1_W_0_1_2_load_reg_791 <= LENET_C1_W_0_1_2_q0;
                LENET_C1_W_0_1_3_load_reg_796 <= LENET_C1_W_0_1_3_q0;
                LENET_C1_W_0_1_4_load_reg_801 <= LENET_C1_W_0_1_4_q0;
                LENET_C1_W_0_2_0_load_reg_806 <= LENET_C1_W_0_2_0_q0;
                LENET_C1_W_0_2_1_load_reg_811 <= LENET_C1_W_0_2_1_q0;
                LENET_C1_W_0_2_2_load_reg_816 <= LENET_C1_W_0_2_2_q0;
                LENET_C1_W_0_2_3_load_reg_821 <= LENET_C1_W_0_2_3_q0;
                LENET_C1_W_0_2_4_load_reg_826 <= LENET_C1_W_0_2_4_q0;
                LENET_C1_W_0_3_0_load_reg_831 <= LENET_C1_W_0_3_0_q0;
                LENET_C1_W_0_3_1_load_reg_836 <= LENET_C1_W_0_3_1_q0;
                LENET_C1_W_0_3_2_load_reg_841 <= LENET_C1_W_0_3_2_q0;
                LENET_C1_W_0_3_3_load_reg_846 <= LENET_C1_W_0_3_3_q0;
                LENET_C1_W_0_3_4_load_reg_851 <= LENET_C1_W_0_3_4_q0;
                LENET_C1_W_0_4_0_load_reg_856 <= LENET_C1_W_0_4_0_q0;
                LENET_C1_W_0_4_1_load_reg_861 <= LENET_C1_W_0_4_1_q0;
                LENET_C1_W_0_4_2_load_reg_866 <= LENET_C1_W_0_4_2_q0;
                LENET_C1_W_0_4_3_load_reg_871 <= LENET_C1_W_0_4_3_q0;
                LENET_C1_W_0_4_4_load_reg_876 <= LENET_C1_W_0_4_4_q0;
                acc_reg_751 <= acc_fu_590_p6;
                    sub_ln131_reg_746(6 downto 1) <= sub_ln131_fu_583_p2(6 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                oc_1_reg_611 <= oc_fu_116;
            end if;
        end if;
    end process;
    sub_ln131_reg_746(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln117_fu_515_p2, grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln117_fu_515_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    LENET_C1_W_0_0_0_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_0_0_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_0_0_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_0_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_0_1_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_0_1_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_0_1_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_0_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_0_2_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_0_2_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_0_2_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_0_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_0_3_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_0_3_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_0_3_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_0_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_0_4_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_0_4_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_0_4_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_0_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_1_0_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_1_0_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_1_0_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_1_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_1_1_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_1_1_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_1_1_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_1_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_1_2_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_1_2_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_1_2_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_1_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_1_3_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_1_3_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_1_3_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_1_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_1_4_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_1_4_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_1_4_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_1_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_2_0_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_2_0_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_2_0_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_2_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_2_1_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_2_1_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_2_1_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_2_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_2_2_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_2_2_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_2_2_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_2_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_2_3_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_2_3_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_2_3_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_2_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_2_4_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_2_4_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_2_4_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_2_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_3_0_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_3_0_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_3_0_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_3_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_3_1_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_3_1_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_3_1_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_3_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_3_2_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_3_2_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_3_2_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_3_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_3_3_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_3_3_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_3_3_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_3_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_3_4_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_3_4_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_3_4_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_3_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_4_0_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_4_0_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_4_0_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_4_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_4_1_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_4_1_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_4_1_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_4_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_4_2_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_4_2_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_4_2_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_4_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_4_3_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_4_3_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_4_3_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_4_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LENET_C1_W_0_4_4_address0 <= zext_ln117_fu_527_p1(2 - 1 downto 0);

    LENET_C1_W_0_4_4_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            LENET_C1_W_0_4_4_ce0 <= ap_const_logic_1;
        else 
            LENET_C1_W_0_4_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln117_fu_521_p2 <= std_logic_vector(unsigned(oc_fu_116) + unsigned(ap_const_lv2_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_done)
    begin
        if ((grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln117_fu_515_p2)
    begin
        if ((((icmp_ln117_fu_515_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln117_fu_515_p2)
    begin
        if (((icmp_ln117_fu_515_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start <= grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_ap_start_reg;
    icmp_ln117_fu_515_p2 <= "1" when (oc_fu_116 = ap_const_lv2_3) else "0";
    sub_ln131_fu_583_p2 <= std_logic_vector(unsigned(zext_ln131_fu_568_p1) - unsigned(zext_ln131_3_fu_579_p1));
    tmp_6_fu_572_p3 <= (oc_1_reg_611 & ap_const_lv1_0);
    tmp_fu_561_p3 <= (oc_1_reg_611 & ap_const_lv4_0);
    x_address0 <= grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_address0;
    x_address1 <= grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_address1;
    x_ce0 <= grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_ce0;
    x_ce1 <= grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_x_ce1;
    y_0_address1 <= grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_address1;
    y_0_ce1 <= grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_ce1;
    y_0_d1 <= grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_d1;
    y_0_we1 <= grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_0_we1;
    y_1_address1 <= grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_address1;
    y_1_ce1 <= grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_ce1;
    y_1_d1 <= grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_d1;
    y_1_we1 <= grp_conv1_pragma_Pipeline_VITIS_LOOP_118_2_VITIS_LOOP_119_3_fu_445_y_1_we1;
    zext_ln117_fu_527_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(oc_fu_116),64));
    zext_ln131_3_fu_579_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_572_p3),7));
    zext_ln131_fu_568_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_561_p3),7));
end behav;
